export const FETCH_ALL_CARDS_REQUEST = 'FETCH_ALL_CARDS_REQUEST';
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS';
export const FETCH_ALL_CARDS_FAILURE = 'FETCH_ALL_CARDS_FAILURE';

export const FETCH_ONE_CARD_REQUEST = 'FETCH_ONE_CARD_REQUEST';
export const FETCH_ONE_CARD_SUCCESS = 'FETCH_ONE_CARD_SUCCESS';
export const FETCH_ONE_CARD_FAILURE = 'FETCH_ONE_CARD_FAILURE';

export const FETCH_BASIC_SET_REQUEST = 'FETCH_BASIC_CARDS_REQUEST';
export const FETCH_BASIC_SET_SUCCESS = 'FETCH_BASIC_CARDS_SUCCESS';
export const FETCH_BASIC_SET_FAILURE = 'FETCH_BASIC_CARDS_FAILURE';
export const FILTER_CARDS_BY_CLASS = 'FILTER_CARDS_BY_CLASS';
