export const FETCH_ALL_CARDS_REQUEST = "FETCH_ALL_CARDS_REQUEST";
export const FETCH_ALL_CARDS_SUCCESS = "FETCH_ALL_CARDS_SUCCESS";
export const FETCH_ALL_CARDS_FAILURE = "FETCH_ALL_CARDS_FAILURE";

export const FETCH_ONE_CARD_REQUEST = "FETCH_ONE_CARD_REQUEST";
export const FETCH_ONE_CARD_SUCCESS = "FETCH_ONE_CARD_SUCCESS";
export const FETCH_ONE_CARD_FAILURE = "FETCH_ONE_CARD_FAILURE";

export const FETCH_EXPANSIONS_CARDS_REQUEST = "FETCH_EXPANSIONS_CARDS_REQUEST";
export const FETCH_EXPANSIONS_CARDS_SUCCESS = "FETCH_EXPANSIONS_CARDS_SUCCESS";
export const FETCH_EXPANSIONS_CARDS_FAILURE = "FETCH_EXPANSIONS_CARDS_FAILURE";
