export const FETCH_ALL_CARDS_REQUEST = 'FETCH_ALL_CARDS_REQUEST';
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS';
export const FETCH_ALL_CARDS_FAILURE = 'FETCH_ALL_CARDS_FAILURE';

export const FETCH_ONE_CARD_REQUEST = 'FETCH_ONE_CARD_REQUEST';
export const FETCH_ONE_CARD_SUCCESS = 'FETCH_ONE_CARD_SUCCESS';
export const FETCH_ONE_CARD_FAILURE = 'FETCH_ONE_CARD_FAILURE';

export const FETCH_BASIC_SET_REQUEST = 'FETCH_BASIC_CARDS_REQUEST';
export const FETCH_BASIC_SET_SUCCESS = 'FETCH_BASIC_CARDS_SUCCESS';
export const FETCH_BASIC_SET_FAILURE = 'FETCH_BASIC_CARDS_FAILURE';

export const FETCH_CURSE_OF_NAXXRAMAS_SET_REQUEST =
  'FETCH_CURSE_OF_NAXXRAMAS_CARDS_REQUEST';
export const FETCH_CURSE_OF_NAXXRAMAS_SET_SUCCESS =
  'FETCH_CURSE_OF_NAXXRAMAS_CARDS_SUCCESS';
export const FETCH_CURSE_OF_NAXXRAMAS_SET_FAILURE =
  'FETCH_CURSE_OF_NAXXRAMAS_CARDS_FAILURE';

export const FETCH_BLACKROCK_MOUNTAIN_SET_REQUEST =
  'FETCH_BLACKROCK_MOUNTAIN_CARDS_REQUEST';
export const FETCH_BLACKROCK_MOUNTAIN_SET_SUCCESS =
  'FETCH_BLACKROCK_MOUNTAIN_CARDS_SUCCESS';
export const FETCH_BLACKROCK_MOUNTAIN_SET_FAILURE =
  'FETCH_BLACKROCK_MOUNTAIN_CARDS_FAILURE';

export const FETCH_THE_GROUND_TOURNAMENT_SET_REQUEST =
  'FETCH_THE_GROUND_TOURNAMENT_CARDS_REQUEST';
export const FETCH_THE_GROUND_TOURNAMENT_SET_SUCCESS =
  'FETCH_THE_GROUND_TOURNAMENT_CARDS_SUCCESS';
export const FETCH_THE_GROUND_TOURNAMENT_SET_FAILURE =
  'FETCH_THE_GROUND_TOURNAMENT_CARDS_FAILURE';

export const FETCH_THE_LEAGUE_OF_EXPLORERS_SET_REQUEST =
  'FETCH_THE_LEAGUE_OF_EXPLORERS_CARDS_REQUEST';
export const FETCH_THE_LEAGUE_OF_EXPLORERS_SET_SUCCESS =
  'FETCH_THE_LEAGUE_OF_EXPLORERS_CARDS_SUCCESS';
export const FETCH_THE_LEAGUE_OF_EXPLORERS_SET_FAILURE =
  'FETCH_THE_LEAGUE_OF_EXPLORERS_CARDS_FAILURE';

export const FETCH_THE_OLD_GODS_SET_REQUEST =
  'FETCH_THE_OLD_GODS_CARDS_REQUEST';
export const FETCH_THE_OLD_GODS_SET_SUCCESS =
  'FETCH_THE_OLD_GODS_CARDS_SUCCESS';
export const FETCH_THE_OLD_GODS_SET_FAILURE =
  'FETCH_THE_OLD_GODS_CARDS_FAILURE';

export const FETCH_THE_KHARAZAN_SET_REQUEST =
  'FETCH_THE_KHARAZAN_CARDS_REQUEST';
export const FETCH_THE_KHARAZAN_SET_SUCCESS =
  'FETCH_THE_KHARAZAN_CARDS_SUCCESS';
export const FETCH_THE_KHARAZAN_SET_FAILURE =
  'FETCH_THE_KHARAZAN_CARDS_FAILURE';

export const FETCH_THE_GADZETAN_SET_REQUEST =
  'FETCH_THE_GADZETAN_CARDS_REQUEST';
export const FETCH_THE_GADZETAN_SET_SUCCESS =
  'FETCH_THE_GADZETAN_CARDS_SUCCESS';
export const FETCH_THE_GADZETAN_SET_FAILURE =
  'FETCH_THE_GADZETAN_CARDS_FAILURE';

export const FETCH_THE_UNGORO_SET_REQUEST = 'FETCH_THE_UNGORO_CARDS_REQUEST';
export const FETCH_THE_UNGORO_SET_SUCCESS = 'FETCH_THE_UNGORO_CARDS_SUCCESS';
export const FETCH_THE_UNGORO_SET_FAILURE = 'FETCH_THE_UNGORO_CARDS_FAILURE';

export const FETCH_THE_FROZEN_THRONE_SET_REQUEST =
  'FETCH_THE_FROZEN_THRONE_CARDS_REQUEST';
export const FETCH_THE_FROZEN_THRONE_SET_SUCCESS =
  'FETCH_THE_FROZEN_THRONE_CARDS_SUCCESS';
export const FETCH_THE_FROZEN_THRONE_SET_FAILURE =
  'FETCH_THE_FROZEN_THRONE_CARDS_FAILURE';
